- name: synchronize embedder model
  hosts: '{{ to_node }}'
  become: false
  tasks:
    - name: rsync installed
      ansible.builtin.package:
        name: rsync
        state: present
      become: true

    - name: Synchronize using rsync command
      ansible.posix.synchronize:
       src: '{{ source }}'
       dest: '{{ destination }}'